// Tüm içerik - sadece haberler, etkinlikler, projeler, blog (statik sayfalar hariç)
export const allContent = [
  // Haberler
  {
    id: "news-1",
    type: "Haber",
    title: "Spor Ekonomisi Raporu 2024 Yayınlandı",
    excerpt: "Türkiye'nin spor ekonomisine ilişkin kapsamlı raporumuz kamuoyuyla paylaşıldı.",
    content: "Türkiye'nin spor ekonomisine ilişkin kapsamlı raporumuz kamuoyuyla paylaşıldı. Raporda spor sektörünün GSYH'ye katkısı, istihdam rakamları ve gelecek projeksiyonları detaylı şekilde analiz edildi. 2024 yılı verileri ekonomi spor sektör",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&auto=format&fit=crop&q=80",
    category: "Araştırma",
    link: "/haber/1",
  },
  {
    id: "news-2",
    type: "Haber",
    title: "Yerel Yönetimler ve Spor Forumu Gerçekleşti",
    excerpt: "Belediyelerin spor politikalarını ele aldığımız forum büyük ilgi gördü.",
    content: "Belediyelerin spor politikalarını ele aldığımız forum büyük ilgi gördü. 50'den fazla belediye temsilcisi katıldı. Forumda yerel yönetimlerin spor politikalarındaki rolü, bütçe planlaması ve tesis yönetimi konuları masaya yatırıldı. belediye yerel yönetim politika",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&auto=format&fit=crop&q=80",
    category: "Etkinlik",
    link: "/haber/2",
  },
  {
    id: "news-3",
    type: "Haber",
    title: "Avrupa Spor Şartı Türkçe'ye Çevrildi",
    excerpt: "Avrupa Konseyi'nin yeni Spor Şartı'nın Türkçe çevirisi derneğimiz tarafından tamamlandı.",
    content: "Avrupa Konseyi'nin yeni Spor Şartı'nın Türkçe çevirisi derneğimiz tarafından tamamlandı. Şart, tüm bireylerin spor yapma hakkını ve sporla ilgili temel ilkeleri içeriyor. Avrupa konsey şart çeviri",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80",
    category: "Yayın",
    link: "/haber/3",
  },
  {
    id: "news-4",
    type: "Haber",
    title: "Gençlik ve Spor Bakanlığı ile Protokol",
    excerpt: "Bakanlık ile spor politikaları alanında işbirliği protokolü imzalandı.",
    content: "Gençlik ve Spor Bakanlığı ile spor politikaları alanında işbirliği protokolü imzalandı. Protokol kapsamında araştırma projeleri, eğitim programları ve politika önerileri geliştirilecek. bakanlık gençlik protokol işbirliği",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&auto=format&fit=crop&q=80",
    category: "Kurumsal",
    link: "/haber/4",
  },
  {
    id: "news-5",
    type: "Haber",
    title: "Spor ve Medya Çalıştayı",
    excerpt: "Medya profesyonelleri ve spor yöneticilerinin katıldığı çalıştay başarıyla tamamlandı.",
    content: "Medya profesyonelleri ve spor yöneticilerinin katıldığı çalıştay başarıyla tamamlandı. Çalıştayda sporun medyada temsili, spor gazeteciliğinin geleceği ve dijital medyanın spor üzerindeki etkileri tartışıldı. medya gazetecilik dijital çalıştay",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80",
    category: "Etkinlik",
    link: "/haber/5",
  },
  {
    id: "news-6",
    type: "Haber",
    title: "Türkiye 2018 Olimpiyatları Analizi ve Performans Raporu",
    excerpt: "Türkiye'nin 2018 olimpik performansına ilişkin detaylı analiz raporumuz yayınlandı.",
    content: "Türkiye'nin 2018 olimpik performansına ilişkin detaylı analiz raporumuz yayınlandı. Raporda Türkiye'nin 2018 olimpiyat tarihindeki başarıları, güçlü ve geliştirilmesi gereken alanlar incelendi. olimpiyat 2018 türkiye performans analiz milli takım sporcular",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&q=80",
    category: "Araştırma",
    link: "/haber/6",
  },
  // Etkinlikler
  {
    id: "event-1",
    type: "Etkinlik",
    title: "Spor ve Gençlik Konferansı 2024",
    excerpt: "Gençlerin spor yoluyla gelişimi üzerine kapsamlı bir konferans.",
    content: "Gençlerin spor yoluyla gelişimi üzerine kapsamlı bir konferans. Eğitim, sağlık ve sosyal gelişim konularında uzmanlar bir araya geliyor. gençlik konferans 2024 gelişim eğitim",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80",
    category: "Konferans",
    link: "/etkinlik/1",
  },
  {
    id: "event-2",
    type: "Etkinlik",
    title: "Yerel Yönetimler Spor Forumu",
    excerpt: "Belediyelerin spor politikaları ve bütçe planlaması üzerine eğitim semineri.",
    content: "Belediyelerin spor politikaları ve bütçe planlaması üzerine eğitim semineri. Yerel yönetimlerin spor tesisi yönetimi konuları. belediye yerel yönetim forum seminer",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&auto=format&fit=crop&q=80",
    category: "Forum",
    link: "/etkinlik/2",
  },
  {
    id: "event-3",
    type: "Etkinlik",
    title: "Spor Bilimleri Araştırma Atölyesi",
    excerpt: "Spor araştırmalarında metodoloji ve veri analizi tekniklerinin öğretildiği atölye.",
    content: "Spor araştırmalarında metodoloji ve veri analizi tekniklerinin öğretildiği atölye. Akademisyenler ve araştırmacılar için. bilim araştırma metodoloji veri analiz atölye",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&auto=format&fit=crop&q=80",
    category: "Atölye",
    link: "/etkinlik/3",
  },
  // Projeler
  {
    id: "project-1",
    type: "Proje",
    title: "Spor ve Toplum Araştırması",
    excerpt: "Türkiye genelinde spor alışkanlıklarını ve spor tesislerine erişimi inceleyen araştırma.",
    content: "Türkiye genelinde spor alışkanlıklarını ve spor tesislerine erişimi inceleyen kapsamlı araştırma projesi. toplum araştırma tesis erişim alışkanlık",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&auto=format&fit=crop&q=80",
    category: "Araştırma",
    link: "/proje/1",
  },
  {
    id: "project-2",
    type: "Proje",
    title: "Yerel Spor Politikaları Rehberi",
    excerpt: "Belediyelere yönelik spor politikası geliştirme rehberi hazırlama projesi.",
    content: "Belediyelere yönelik spor politikası geliştirme rehberi hazırlama projesi. belediye yerel politika rehber",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&auto=format&fit=crop&q=80",
    category: "Eğitim",
    link: "/proje/2",
  },
  {
    id: "project-3",
    type: "Proje",
    title: "Spor Ekonomisi İzleme Sistemi",
    excerpt: "Türkiye'nin spor ekonomisini takip eden dijital platform geliştirme projesi.",
    content: "Türkiye'nin spor ekonomisini takip eden dijital platform geliştirme projesi. ekonomi izleme sistem dijital platform",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&auto=format&fit=crop&q=80",
    category: "Teknoloji",
    link: "/proje/3",
  },
  {
    id: "project-4",
    type: "Proje",
    title: "Kadın Sporcu Destek Programı",
    excerpt: "Kadın sporcuların kariyer gelişimini destekleyen mentorluk ve eğitim programı.",
    content: "Kadın sporcuların kariyer gelişimini destekleyen mentorluk ve eğitim programı. kadın sporcu kariyer mentorluk eğitim",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&auto=format&fit=crop&q=80",
    category: "Sosyal",
    link: "/proje/4",
  },
  {
    id: "project-5",
    type: "Proje",
    title: "Okul Sporları Analiz Raporu",
    excerpt: "Türkiye'deki okul sporları sisteminin kapsamlı analizi ve politika önerileri.",
    content: "Türkiye'deki okul sporları sisteminin kapsamlı analizi ve politika önerileri. okul eğitim analiz rapor politika",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80",
    category: "Araştırma",
    link: "/proje/5",
  },
  {
    id: "project-6",
    type: "Proje",
    title: "Engelli Sporları Erişilebilirlik Projesi",
    excerpt: "Engelli bireylerin spora erişimini artırmaya yönelik araştırma ve savunuculuk projesi.",
    content: "Engelli bireylerin spora erişimini artırmaya yönelik kapsamlı araştırma ve savunuculuk projesi. engelli erişilebilirlik paralimpik destek",
    author: "SPOLDER",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&q=80",
    category: "Sosyal",
    link: "/proje/6",
  },
  // Blog Yazıları
  {
    id: "blog-1",
    type: "Blog",
    title: "Spor Politikalarında Yeni Yaklaşımlar",
    excerpt: "Modern spor politikalarının toplum üzerindeki etkilerini ve gelecek vizyonunu ele alan analiz.",
    content: "Modern spor politikalarının toplum üzerindeki etkilerini ve gelecek vizyonunu ele alan kapsamlı bir analiz. politika modern yaklaşım toplum vizyon",
    author: "Dr. Ahmet Yılmaz",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&h=400&fit=crop",
    category: "Analiz",
    link: "/blog/1",
  },
  {
    id: "blog-2",
    type: "Blog",
    title: "Kadın Sporculara Destek Programları",
    excerpt: "Türkiye'de kadın sporcuların karşılaştığı zorluklar ve çözüm önerileri.",
    content: "Türkiye'de kadın sporcuların karşılaştığı zorluklar ve çözüm önerileri üzerine bir değerlendirme. kadın sporcu destek program zorluk",
    author: "Prof. Elif Kaya",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop",
    category: "Araştırma",
    link: "/blog/2",
  },
  {
    id: "blog-3",
    type: "Blog",
    title: "Spor ve Sürdürülebilirlik",
    excerpt: "Çevre dostu spor tesisleri ve sürdürülebilir spor etkinlikleri.",
    content: "Çevre dostu spor tesisleri ve sürdürülebilir spor etkinlikleri hakkında güncel gelişmeler. çevre sürdürülebilirlik yeşil enerji",
    author: "Mehmet Demir",
    image: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600&h=400&fit=crop",
    category: "Görüş",
    link: "/blog/3",
  },
  {
    id: "blog-4",
    type: "Blog",
    title: "Dijital Dönüşüm ve Spor",
    excerpt: "Teknolojinin spor dünyasındaki dönüştürücü etkisi ve geleceğe yönelik öngörüler.",
    content: "Teknolojinin spor dünyasındaki dönüştürücü etkisi ve geleceğe yönelik öngörüler. dijital teknoloji yapay zeka veri analiz",
    author: "Zeynep Arslan",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&h=400&fit=crop",
    category: "Teknoloji",
    link: "/blog/4",
  },
  {
    id: "blog-5",
    type: "Blog",
    title: "Engelli Sporculara Eşit Fırsatlar",
    excerpt: "Engelli bireylerin spora erişimi ve paralimpik hareketin Türkiye'deki gelişimi.",
    content: "Engelli bireylerin spora erişimi ve paralimpik hareketin Türkiye'deki gelişimi. engelli paralimpik erişim fırsat eşitlik",
    author: "Ali Öztürk",
    image: "https://images.unsplash.com/photo-1591343395082-e120087004b4?w=600&h=400&fit=crop",
    category: "Sosyal",
    link: "/blog/5",
  },
  {
    id: "blog-6",
    type: "Blog",
    title: "Gençlik ve Spor Kültürü",
    excerpt: "Z kuşağının spor alışkanlıkları ve spor kültürünün gençler arasında yaygınlaştırılması.",
    content: "Z kuşağının spor alışkanlıkları ve spor kültürünün gençler arasında yaygınlaştırılması. gençlik z kuşağı kültür alışkanlık sosyal medya",
    author: "Selin Yıldız",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&h=400&fit=crop",
    category: "Gençlik",
    link: "/blog/6",
  },
];

// Arama fonksiyonu
export function searchContent(query: string) {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return allContent.filter(
    (item) =>
      item.title.toLowerCase().includes(q) ||
      item.excerpt.toLowerCase().includes(q) ||
      item.content.toLowerCase().includes(q) ||
      item.category.toLowerCase().includes(q) ||
      item.author.toLowerCase().includes(q)
  );
}
